[influx]
    bucket = 'bucket'
    org = 'org'
    token = 'token'
    uri = 'uri'

[measurement]
    name = 'measurement'

[fields]
    StartTime = 'StartTime'
    EndTime = 'EndTime'
    bits = 'Metrics/bits'


[tags]
    AlarmID = 'AlarmID'
    AlarmPolicyId = 'AlarmPolicyId'
    AlarmPolicyName = 'AlarmPolicyName'
    AlarmThresholdID = 'AlarmThresholdID'
    IP_dst_cidr = 'Dimensions/IP_dst_cidr_.*'
    Port_dst = 'Dimensions/Port_dst'
    Proto = 'Dimensions/Proto'

[exclude]
    EndTime = 'ongoing'

[process.fields]
    StartTime = 'unixtime'
    EndTime = 'unixtime'
    
[process.tags]


#[[postprocess]]
#    [postprocess.match]
#       type = <field|tag>
#       name = <field_or_tag_name>
#       regex = <regex>
#    [postprocess.target]
#       type = <field|tag>
#       name = <tag_or_field_name>
#       value = <value_to_assign>


[[postprocess]]
    [postprocess.match]
        type = 'tag'
        name = 'IP_dst_cidr'
        regex = '177\.234\..*'
    [postprocess.target]
        type = 'tag'
        name = 'servicio'
        value = 'premium'


[[postprocess]]
    [postprocess.match]
        type = 'tag'
        name = 'IP_dst_cidr'
        regex = '192\.168\..*'
    [postprocess.target]
        type = 'tag'
        name = 'servicio'
        value = 'base'
